[workspace]
authors = ["JupiterPi <hello@jupiterpi.de>", "Pascal Roth", "Gregor Niehl <gregorniehl@web.de>"]
channels = ["robostack-jazzy", "conda-forge"]
name = "crawler-controller"
platforms = ["linux-aarch64", "linux-64"]
version = "0.1.0"

[tasks]
upload = "scripts/upload.sh"
build-web = "scripts/build-and-install-web.sh"
build-ros = "colcon build"
launch = "ros2 launch crawler.launch"
launch-web-api = "ros2 run crawler crawler_web_api"
launch-blinker = "ros2 run crawler crawler_blinker"

[activation]
scripts = ["install/setup.sh"]

[dependencies]
python = ">=3.11.11,<3.12"
flask = ">=3.1.0,<4"
flask_cors = ">=4.0.0,<5"
ros-jazzy-desktop = ">=0.11.0,<0.12"
colcon-common-extensions = ">=0.3.0,<0.4"
setuptools = ">=78.1.0,<79"
nodejs = ">=22.13.0,<22.14"

[pypi-dependencies]
rpi-gpio = ">=0.7.1, <0.8"
luma-core = ">=2.4.2, <3"
luma-oled = ">=3.14.0, <4"
flask-sock = ">=0.7.0"

[feature.dev.dependencies]
ruff = "*"
jedi-language-server = "*"
python-lsp-server-base = "*"
python-lsp-server = "*"

[environments]
default = ["dev"]
