[workspace]
authors = ["JupiterPi <hello@jupiterpi.de>", "Pascal Roth", "Gregor Niehl <gregorniehl@web.de>"]
channels = ["robostack-jazzy", "conda-forge"]
name = "crawler-controller"
platforms = ["linux-aarch64", "linux-64"]
version = "0.1.0"


[tasks]

# upload source to Pi
upload = "scripts/upload.sh"

# build crawler-web-ui and ROS package
build-web = "scripts/build-and-install-web.sh"
build-ros = "scripts/build-ros.sh"

# start on the Pi
start-rpi = "scripts/start-rpi.sh"

# launch ROS nodes directly
launch = "ros2 launch crawler.launch" # all
launch-web-api = "ros2 run crawler crawler_web_api"
launch-blinker = "ros2 run crawler crawler_blinker"
launch-motors = "ros2 run crawler crawler_motors"

# for development
dev-ros = { depends-on = ["build-ros"], cmd = "export CRAWLER_ENV=dev && ros2 launch crawler.launch" }
dev-web = "cd crawler-web-ui && npm run dev"


[activation]
scripts = ["build-env.sh", "install/setup.sh"]

[dependencies]
python = ">=3.12.11,<3.13"
flask = ">=3.1.1,<4"
flask_cors = ">=4.0.0,<5"
ros-jazzy-desktop = ">=0.11.0,<0.12"
colcon-common-extensions = ">=0.3.0,<0.4"
setuptools = ">=80.9.0,<81"
nodejs = ">=24.4.0,<24.5"
keras = ">=3.10.0,<4"
numpy = ">=1.26.4,<2"
# ros-jazzy-dynamixel-sdk = ">=3.8.4,<4" # We seemed to encounter issues with this, so using pypi version for now

[pypi-dependencies]
rpi-gpio = ">=0.7.1, <0.8"
luma-core = ">=2.4.2, <3"
luma-oled = ">=3.14.0, <4"
flask-sock = ">=0.7.0, <0.8"
gpiozero = ">=2.0.1, <3"
dynamixel-sdk = ">=3.7.31, <4"
## rpi-only ## "rpi-lgpio" = ">=0.0.6"

[feature.dev.dependencies]
types-setuptools = ">=79.0.0.20250422,<80"
types-flask = ">=1.1.6,<2"
jedi-language-server = ">=0.45.1,<0.46"
ruff = ">=0.13.0,<0.14"
typescript-language-server = ">=4.3.4,<5"
rsync = ">=3.4.1,<4"

[feature.dev.pypi-dependencies]
types-flask-cors = ">=5.0.0.20250413, <6"
types-torch = ">=0.1.1, <0.2"
ty = ">=0.0.1a20, <0.0.1a21"

[environments]
default = ["dev"]
raspi = []
