[workspace]
authors = ["JupiterPi <hello@jupiterpi.de>", "Pascal Roth", "Gregor Niehl <gregorniehl@web.de>"]
channels = ["robostack-jazzy", "conda-forge"]
name = "crawler-controller"
platforms = ["linux-aarch64", "linux-64"]
version = "0.1.0"


[tasks]

# upload source to Pi
upload = "scripts/upload.sh"

# build crawler-web-ui and ROS package
build-web = "scripts/build-and-install-web.sh"
build-ros = "scripts/build-ros.sh"

# start on the Pi
start-rpi = "scripts/start-rpi.sh"

# launch ROS nodes directly
launch = "ros2 launch crawler.launch" # all
launch-web-api = "ros2 run crawler crawler_web_api"
launch-blinker = "ros2 run crawler crawler_blinker"
launch-motors = "ros2 run crawler crawler_motors"

# for development
dev-ros = { depends-on = ["build-ros"], cmd = "export CRAWLER_ENV=dev && ros2 launch crawler.launch" }
dev-web = "cd crawler-web-ui && npm run dev"


[activation]
scripts = ["build-env.sh", "install/setup.sh"]

[dependencies]
python = ">=3.11.11,<3.12"
flask = ">=3.1.0,<4"
flask_cors = ">=4.0.0,<5"
ros-jazzy-desktop = ">=0.11.0,<0.12"
colcon-common-extensions = ">=0.3.0,<0.4"
setuptools = ">=78.1.0,<79"
nodejs = ">=22.13.0,<22.14"
pytorch = ">=2.6.0,<3"

[pypi-dependencies]
rpi-gpio = ">=0.7.1, <0.8"
luma-core = ">=2.4.2, <3"
luma-oled = ">=3.14.0, <4"
flask-sock = ">=0.7.0"
gpiozero = ">=2.0.1"
dynamixel-sdk = ">=3.7.31, <4"
"rpi-lgpio" = ">=0.0.6"

[feature.dev.dependencies]
python-lsp-server-base = "*"
python-lsp-server = "*"
pylsp-mypy = ">=0.6.6,<0.7"
python-lsp-ruff = ">=2.2.2,<3"
pyls-memestra = ">=0.0.16,<0.0.17"
types-setuptools = ">=79.0.0.20250422,<80"
types-flask = ">=1.1.6,<2"

[feature.dev.pypi-dependencies]
types-flask-cors = ">=5.0.0.20250413, <6"
types-torch = ">=0.1.1, <0.2"

[environments]
default = ["dev"]
