[workspace]
authors = ["JupiterPi <hello@jupiterpi.de>", "Pascal Roth", "Gregor Niehl <gregorniehl@web.de>"]
channels = ["robostack-jazzy", "conda-forge"]
name = "crawler-controller"
platforms = ["linux-aarch64", "linux-64"]
version = "0.1.0"


[tasks]

# upload source to Pi
upload = "scripts/upload.sh"

# build crawler-web-ui and ROS package
build-web = "scripts/build-and-install-web.sh"
build-ros = "scripts/build-ros.sh"

# launch ROS nodes
launch = "ros2 launch crawler.launch" # all
launch-web-api = "ros2 run crawler crawler_web_api"
launch-blinker = "ros2 run crawler crawler_blinker"
launch-motors = "ros2 run crawler crawler_motors"

# for development
dev-ros = { depends-on = ["build-ros"], cmd = "export CRAWLER_ENV=dev && ros2 launch crawler.launch" }
dev-web = "cd crawler-web-ui && npm run dev"


[activation]
scripts = ["build-env.sh", "install/setup.sh"]

[dependencies]
python = ">=3.11.11,<3.12"
flask = ">=3.1.0,<4"
flask_cors = ">=4.0.0,<5"
ros-jazzy-desktop = ">=0.11.0,<0.12"
colcon-common-extensions = ">=0.3.0,<0.4"
setuptools = ">=78.1.0,<79"
nodejs = ">=22.13.0,<22.14"

[pypi-dependencies]
rpi-gpio = ">=0.7.1, <0.8"
luma-core = ">=2.4.2, <3"
luma-oled = ">=3.14.0, <4"
flask-sock = ">=0.7.0"
gpiozero = ">=2.0.1"
## rpi-only ## "rpi-lgpio" = ">=0.0.6"

[feature.dev.dependencies]
ruff = "*"
jedi-language-server = "*"
python-lsp-server-base = "*"
python-lsp-server = "*"

[environments]
default = ["dev"]
